### PR TITLE
stack: add support for 1.18 stack traces

### LINKED ISSUE #73: Make panicparse compatible with go1.18beta1
I'm seeing arguments with a trailing ?:

```
testing.(*T).Run(0xc0001b61a0, {0x610e19?, 0x4f8c65?}, 0x61cc68)
        /path/to/golang/src/testing/testing.go:1458 +0x37a
```

### PR DESCRIPTION
**Pull request by MordFustang21**
Go 1.18 introduced  a ? to annotate an inaccurate value in stack traces. This code should resolve that let me know if there are any places I've missed or tests that I should add to better handle it.

Resolves #73

### CODE REVIEW

File: stack/context.go [hunk 1]
```diff
@@ -854,13 +855,19 @@ func parseArgs(line []byte) (Args, error) {
 				arg := Arg{IsOffsetTooLarge: true}
 				cur.Values = append(cur.Values, arg)
 			default:
+				var inaccurate bool
```
Comment (maruel) [inline stack/context.go:858]: I prefer something like:

```
inaccurate := bytes.HasSuffix(a, inaccurateQuestionMark)
if inaccurate {
  a = a[:len(a)-1]
}
```

File: stack/context_test.go [hunk 2]
```diff
@@ -21,6 +21,7 @@ import (
 	"testing"
 
 	"github.com/google/go-cmp/cmp"
+
```
Comment (maruel) [inline stack/context_test.go:24]: Please undo.

**Review by maruel — COMMENTED** [review]
This was actually broken in go1.17; https://go.dev/doc/go1.17#compiler but forgot to file a bug about it. Let's keep this change and reassign it to fix this separate bug.

File: stack/context.go [hunk 3]
```diff
@@ -321,7 +322,7 @@ var (
 	reRaceGoroutine = regexp.MustCompile(`^Goroutine (\d+) \((running|finished)\) created at:$`)
 
 	// TODO(maruel): Use it.
-	//reRacePreviousOperationMainHeader = regexp.MustCompile("^Previous (read|write) at (0x[0-9a-f]+) by main goroutine:$")
+	// reRacePreviousOperationMainHeader = regexp.MustCompile("^Previous (read|write) at (0x[0-9a-f]+) by main goroutine:$")
```
Comment (maruel) [inline stack/context.go:325]: Is it your IDE that did that? I use this form for explicitly commented out code and would prefer to not change these lines here.

Comment (MordFustang21) [reply stack/context.go:325]: Yeah sorry I can undo that. It defaults to adding spaces at the beginning of comments.

File: stack/context.go (hunk 1 above)
Comment (MordFustang21) [reply stack/context.go:858]: I like that better too. Fixing.

File: stack/context.go [hunk 4]
```diff
@@ -854,13 +855,18 @@ func parseArgs(line []byte) (Args, error) {
 				arg := Arg{IsOffsetTooLarge: true}
 				cur.Values = append(cur.Values, arg)
 			default:
+				inaccurate := bytes.HasSuffix(a, inaccurateQuestionMark)
+				if inaccurate {
+					a = a[:len(a)-1]
```
[the remark this answers is not in the document]
Comment (MordFustang21) [reply stack/context.go]: Changed

**Comment by tommie** [comment]
@maruel Thanks for writing this library. I'm using it to check for leaking goroutines in tests.

I just hit this question mark issue and was wondering if it will be made into a v2.2.1 release soon.

**Comment by maruel** [comment]
No sorry I haven't done the release yet. I wanted to change cmd/panic/main.go so reduce recursiveness conditionally so I could make tests pass on 1.18. See linked bug.
